http:
  # 最大连接数
  maxTotal: 200
  # 单个路由最大连接数
  defaultMaxPerRoute: 50
  # 连接上服务器(握手成功)的时间，超出抛出connect timeout
  connectTimeout: 5000
  connectionRequestTimeout: 5000
  # 服务器返回数据(response)的时间，超过抛出read timeout
  socketTimeout: 5000
  # 提交前检测是否可用
  staleConnectionCheckEnabled: true
  # 最大空闲时间
  validateAfterInactivity: 5000
url:
  # 推送供暖信息数据url
  pushCollect: http://49.233.38.90/api/collect/data/pushCollect?ak=ebf556cf95807bbf5c64d572c706107a
  # 获取已推送供暖信息数据url
  getCollect: http://49.233.38.90/api/collect/data/getCollect?ak=ebf556cf95807bbf5c64d572c706107a
server:
  port: 8081
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    static-path-pattern: /static/

